language: go
sudo: true # needed to install the pulsar-client-cpp
dist: xenial

go:
 - 1.11.x
 - master

env:
 - GO111MODULE=on

before_install:
  - wget -O pulsar-client-cpp.deb http://apache.panu.it/pulsar/pulsar-2.3.1/DEB/apache-pulsar-client.deb
  - wget -O pulsar-client-dev.deb http://apache.panu.it/pulsar/pulsar-2.3.1/DEB/apache-pulsar-client-dev.deb
  - sudo apt install ./pulsar-client-cpp.deb ./pulsar-client-dev.deb

script:
  - go get -v -t ./...
  # hack for counter the https://github.com/apache/pulsar/issues/4055
  - git clone --branch v2.3.1 https://github.com/apache/pulsar.git
  - sudo cp -r pulsar/pulsar-client-go/pulsar $GOPATH/pkg/mod/github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190502042238-97bc7e07aedf/pulsar
  - go test -v ./...

after_success:
 - go test -cover ./...
